---
# tasks file for roles/flexget

  - name: apt-get stuff
    apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
    with_items:
      - python-pip

  - name: intall pip stuff
    pip: name={{ item }} state=present
    with_items:
      - https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55
      - flexget

  - name: add flexget user
    user: name=flexget state=present

  - name: deploy flexget config
    get_url: url={{ flexget_conf_url }} dest=/home/flexget/config.yml owner=flexget group=flexget

  - name: setup config wget cron
    become_user: flexget
    cron:
      minute=0
      name="Updated config"
      job="wget {{ flexget_conf_url }} -O /home/flexget/config.yml"

  - name: setup flexget cronjob
    become_user: flexget
    cron:
      minute=10
      name="Flexget download stuff"
      job="/usr/local/bin/flexget --cron -c /home/flexget/config.yml execute"

